### ISSUE TITLE
View is getting disappeared while click on icon

### ISSUE THREAD

**Issue by AhtashamAnsari0** [jayrambhia/Tooltip#19] opened 2020-05-06 11:10 UTC
I used Tooltip.builder() in Fragment but when I click on ImageView it shows and after showing whole it gets disappeared in just a second? Please suggest me.

Please find logs here:
2020-05-06 16:36:19.390 25288-25288/com.ikea.tradfri.lighting I/Tooltip: child layout: left: 435 top: -759 right: 794 bottom: -682
2020-05-06 16:36:19.391 25288-25288/com.ikea.tradfri.lighting I/Tooltip: px: 767, py: -771
2020-05-06 16:36:19.392 25288-25288/com.ikea.tradfri.lighting D/Tooltip: anchor point: 767, -771
2020-05-06 16:36:19.392 25288-25288/com.ikea.tradfri.lighting D/Tooltip: size: 359, 77
2020-05-06 16:36:51.415 25288-25288/com.ikea.tradfri.lighting I/Tooltip: l: 0, t: 849, r: 824, b: 849
2020-05-06 16:36:51.447 25288-25288/com.ikea.tradfri.lighting I/Tooltip: onPreDraw: 940, 595
2020-05-06 16:36:51.447 25288-25288/com.ikea.tradfri.lighting D/Tooltip: anchor location: 940, 595
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: holder location: 188, 1402
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: child w: 359 h: 77
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: left: 752, top: -807
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip top Before: -807
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip top: -759
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip Move to: 767 -771
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip Line to: 761 -759
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip Line to: 773 -759
2020-05-06 16:36:51.448 25288-25288/com.ikea.tradfri.lighting D/Tooltip: tip Line to: 767 -771
2020-05-06 16:36:51.449 25288-25288/com.ikea.tradfri.lighting I/Tooltip: child layout: left: 435 top: -759 right: 794 bottom: -682
2020-05-06 16:36:51.449 25288-25288/com.ikea.tradfri.lighting I/Tooltip: px: 767, py: -771
2020-05-06 16:36:51.451 25288-25288/com.ikea.tradfri.lighting D/Tooltip: anchor point: 767, -771
2020-05-06 16:36:51.452 25288-25288/com.ikea.tradfri.lighting D/Tooltip: size: 359, 77
2020-05-06 16:36:54.729 25288-25288/com.ikea.tradfri.lighting I/Tooltip: canvas w: 824, h: 0

private void showCustomTooltip(@NonNull View anchor) {
   
        @SuppressLint("InflateParams") View content = getLayoutInflater().inflate(R.layout.item_tooltip_view_1, null);
        Resources res = getResources();

        int tooltipPadding = res.getDimensionPixelOffset(R.dimen.tooltip_padding);
        int tooltipColor = ContextCompat.getColor(mBaseActivity, R.color.warning_text_color);
        int tipSizeSmall = res.getDimensionPixelSize(R.dimen.tip_dimen_small);
        int tipRadius = res.getDimensionPixelOffset(R.dimen.tip_radius);

        customTooltip = new Tooltip.Builder(getActivity())
                .anchor(anchor, Tooltip.BOTTOM)
                .animate(new TooltipAnimation(TooltipAnimation.SCALE_AND_FADE, 400))
                .autoAdjust(true)
                .withPadding(tooltipPadding)
                .withMargin(6)
                .content(content)
                .cancelable(true)
                .checkForPreDraw(true)
                .withTip(new Tooltip.Tip(tipSizeSmall, tipSizeSmall, tooltipColor))
                .into(mRootLayout)
                .debug(true)
                .show();
    }

**Comment by jayrambhia** [comment] 2020-05-08 09:53
Duplicate of #20

**Closed as completed by jayrambhia** 2020-05-08 09:53 UTC
